= Lab/Walkthrough instructions - Container Builds

img

== Prereqs

Mandatory:

* A Docker environment and Docker CLI https://docs.docker.com/get-docker/
* Pack CLI for Cloud-Native Buildpacks https://buildpacks.io/docs/tools/pack/
* Clone this repo https://github.com/maeddes/options-galore-container-build

Recommended:

* A Java (11 or later) Development Kit for Java examples, e.g https://adoptopenjdk.net/

Optional:

* Dive tool https://github.com/wagoodman/dive

=== Validation

Validate docker installation.

----
docker version
----

Should display output like (version might differ):

----
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
...

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
----

Validate Java.

----
java --version
----

Should display output like (version might differ):

----
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
----

== Dockerfile Exercises

=== Classic

Set to classic Docker mode:

[source, bash]

----
export DOCKER_BUILDKIT=0
----

Build the code:

Change to the Java sample app directory
----
cd java
----

Option 1 (with local JDK installed)
----
./mvnw clean package
----

Option 2 (with local JDK installed - using docker)
----
docker run -it --rm --name my-maven-project -v "$(pwd)":/opt/app -w /opt/app maven:3.6.3-jdk-11 mvn clean install
----

Validate build artefact
----
ls -ltr ./target/simplecode-0.0.1-SNAPSHOT.jar
-rw-r--r--  1 mhs  staff  18985578 Nov 26 10:24 ./target/simplecode-0.0.1-SNAPSHOT.jar
----

Observe contents of Dockerfile-simple-ubuntu

----
cat Dockerfile-simple-ubuntu

FROM ubuntu:20.10
RUN apt update && apt install openjdk-11-jre-headless -y
COPY target/simplecode-0.0.1-SNAPSHOT.jar /opt/app.jar
CMD ["java","-jar","/opt/app.jar"]
----

Build first image with this Dockerfile:

----
docker build -f Dockerfile-simple-ubuntu -t java-app:v-simple-ubuntu .
----

Build images with other predefined base images:

----
docker build -f Dockerfile-simple-adoptopenjdk -t java-app:v-simple-adoptopenjdk .
----

----
docker build -f Dockerfile-simple-openjdk -t java-app:v-simple-openjdk .
----

Validate images in local repo

----
docker images
...
----

Observe build history and differences of the 3 images

----
docker history java-app:v-simple-ubuntu
docker history java-app:v-simple-adoptopenjdk
docker history java-app:v-simple-openjdk
----

Optional: Use tool "dive" to show detailed history of image:

----
dive java-app:v-simple-ubuntu
dive java-app:v-simple-adoptopenjdk
dive java-app:v-simple-openjdk
----

Use ctrl+m || ctrl+u

=== Multi-Stage

Build image with Multistage Dockerfile:

----
docker build -f Dockerfile-multistage-builder -t maeddes/java-app:v-multistage-builder .
----

Validate history:

----
docker history maeddes/java-app:v-multistage-builder
----

=== BuildKit

Change to new Docker mode:

----
export DOCKER_BUILDKIT=1
----

optional: remove maven and openjdk container image and show parallel download of images

----
docker build -f Dockerfile-multistage-builder -t maeddes/java-app:v-multistage-builder . 
----

Alternative output

----
docker build --progress=plain -f Dockerfile-multistage-builder -t maeddes/java-app:v-multistage-builder .
----

change code - run again

----
docker build -f Dockerfile-multistage-experimental-cache -t maeddes/ava-app:v-multistage-experimental-cache .
----

Alternative output

----
docker build --progress=plain -f Dockerfile-multistage-builder -t maeddes/java-app:v-multistage-builder .
----

change code - run again

show unlayered state

----
docker history maeddes/ava-app:v-multistage-experimental-cache
----

change code - run again

----
docker build -f Dockerfile-multistage-layered -t maeddes/java-app:layered .
----

show layered state

----
docker history maeddes/java-app:layered
----

== Jib

Again the use of the local maven wrapper (mvnw) will require a local JDK installation.
If it's not present use option 2.

----
mvn compile com.google.cloud.tools:jib-maven-plugin:3.0.0:dockerBuild -Dimage=java-app:jib
----

----
docker run -it --rm --name my-maven-project -v "$(pwd)":/opt/app -w /opt/app maven:3.6.3-jdk-11 mvn compile com.google.cloud.tools:jib-maven-plugin:3.0.0:buildTar -Dimage=maeddes/java-app:jib
----

----
docker history maeddes/java-app:jib
----

== Cloud-native buildpacks

----
pack builder suggest
----

----
pack set-default-builder paketobuildpacks/builder:base (deprecated)
pack config default-builder paketobuildpacks/builder:base 
----

----
pack build maeddes/java-app:pack
----

== Paketo

----
mvn spring-boot:build-image -Dspring-boot.build-image.imageName=maeddes/java-app:paketo
----

