= Lab/Walkthrough instructions - Container Builds

img

== Prereqs

* A Docker environment and Docker CLI https://docs.docker.com/get-docker/
* A Java (11 or later) Development Kit for Java examples, e.g https://adoptopenjdk.net/
* Pack CLI for Cloud-Native Buildpacks https://buildpacks.io/docs/tools/pack/
* Clone this repo https://github.com/maeddes/options-galore-container-build

Optional:

* Dive tool https://github.com/wagoodman/dive

=== Validation

Validate docker installation.

----
docker version
----

Should display output like (version might differ):

----
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
...

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
----

Validate Java.

----
java --version
----

Should display output like (version might differ):

----
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
----

== Dockerfile Exercises

=== Classic

Set to classic Docker mode:

[source, bash]

----
export DOCKER_BUILDKIT=0
----

Build the code:

----
cd java
./mvnw clean package
----

Observe contents of Dockerfile-simple-ubuntu

----
cat Dockerfile-simple-ubuntu

FROM ubuntu:20.10
RUN apt update && apt install openjdk-11-jre-headless -y
COPY target/simplecode-0.0.1-SNAPSHOT.jar /opt/app.jar
CMD ["java","-jar","/opt/app.jar"]
----

Build first image with this Dockerfile:

----
docker build -f Dockerfile-simple-ubuntu -t java-app:v-simple-ubuntu .
----

Show history of image:

----
docker history java-app:v-simple-ubuntu
----

Build image with predefined base image:

----
docker build -f Dockerfile-simple-adoptopenjdk -t java-app:v-simple-adoptopenjdk .
----

Build image with alternative base image:

----
docker history maeddes/java-app:v-simple-adoptopenjdk
----

Use tool "dive" to show detailed history of image:

----
dive maeddes/java-app:v-simple-ubuntu
dive maeddes/java-app:v-simple-adoptopenjdk
----

Use ctrl+m || ctrl+u

=== Multi-Stage

Build image with Multistage Dockerfile:

----
docker build -f Dockerfile-multistage-builder -t maeddes/java-app:v-multistage-builder .
----

Validate history:

----
docker history maeddes/java-app:v-multistage-builder
----

=== BuildKit

Change to new Docker mode:

----
export DOCKER_BUILDKIT=1
----

optional: remove maven and openjdk container image and show parallel download of images

----
docker build -f Dockerfile-multistage-builder -t maeddes/java-app:v-multistage-builder . 
----

Alternative output

----
docker build --progress=plain -f Dockerfile-multistage-builder -t maeddes/java-app:v-multistage-builder .
----

change code - run again

----
docker build -f Dockerfile-multistage-experimental-cache -t maeddes/ava-app:v-multistage-experimental-cache .
----

change code - run again

show unlayered state

----
docker history maeddes/ava-app:v-multistage-experimental-cache
----

change code - run again

----
docker build -f Dockerfile-multistage-layered -t maeddes/java-app:layered .
----

show layered state

----
docker history maeddes/java-app:layered
----

== Jib

----
mvn compile com.google.cloud.tools:jib-maven-plugin:3.0.0:build -Dimage=maeddes/java-app:jib
----

show no image locally with this tag

https://hub.docker.com/

----
mvn compile com.google.cloud.tools:jib-maven-plugin:3.0.0:dockerBuild -Dimage=maeddes/java-app:jib
----
----
mvn clean package com.google.cloud.tools:jib-maven-plugin:3.0.0:dockerBuild -Dimage=maeddes/java-app:jib
----

----
docker history maeddes/java-app:jib
----

== Cloud-native buildpacks

----
pack build maeddes/java-app:pack
----

----
pack builder suggest
----

----
pack set-default-builder paketobuildpacks/builder:tiny (deprecated)
pack config default-builder paketobuildpacks/builder:tiny 
----

== Paketo

----
mvn spring-boot:build-image -Dspring-boot.build-image.imageName=maeddes/java-app:paketo
----

== Native-Images

----
pack build maeddes/java-app:native --env BP_NATIVE_IMAGE=true
gradle bootBuildImage
----

== Micronaut

----
pack build maeddes/micronaut-app:paketo
----

== s2i

----
s2i build --copy . fabric8/s2i-java:latest-java11 maeddes/java-app:s2i --incremental
----

