
FROM maven:3-eclipse-temurin-17 AS build
RUN mkdir -p /opt/app/src
COPY src /opt/app/src
COPY pom.xml /opt/app
RUN --mount=type=cache,target=/root/.m2 mvn -f /opt/app/pom.xml clean package
# RUN mvn -f /opt/app/pom.xml clean package

FROM eclipse-temurin:17-jre
RUN useradd -ms /bin/bash newuser
USER newuser
COPY --from=build /opt/app/target/simplecode-0.0.1-SNAPSHOT.jar /opt/app.jar
CMD ["java","-jar","/opt/app.jar"]
