FROM maven:3-eclipse-temurin-17 as build
RUN mkdir /opt/app
COPY src /opt/app/src
COPY pom.xml /opt/app
WORKDIR /opt/app
RUN --mount=type=cache,target=/root/.m2 mvn package -DskipTests
RUN jar xf target/simplecode-0.0.1-SNAPSHOT.jar
RUN jdeps --ignore-missing-deps -q  \
    --recursive  \
    --multi-release 17  \
    --print-module-deps  \
    --class-path 'BOOT-INF/lib/*'  \
    target/simplecode-0.0.1-SNAPSHOT.jar > deps.info
RUN jlink \
    --add-modules $(cat deps.info) \
    --strip-debug \
    --compress 2 \
    --no-header-files \
    --no-man-pages \
    --output /myjre

FROM eclipse-temurin:17-jre as extractor
RUN mkdir /opt/app
WORKDIR /opt/app
COPY --from=build /opt/app/target/simplecode-0.0.1-SNAPSHOT.jar application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM ubuntu:jammy
ENV JAVA_HOME /opt/java/jdk17
ENV PATH $JAVA_HOME/bin:$PATH
COPY --from=build /myjre $JAVA_HOME
RUN mkdir /opt/app
WORKDIR /opt/app
COPY --from=extractor /opt/app/dependencies/ ./
COPY --from=extractor /opt/app/spring-boot-loader/ ./
COPY --from=extractor /opt/app/snapshot-dependencies/ ./
COPY --from=extractor /opt/app/application/ ./
ENTRYPOINT ["java","-XX:+UseParallelGC","-XX:MaxRAMPercentage=75","org.springframework.boot.loader.JarLauncher"]